remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: LEGEND
logo: /assets/img/logo.png
description: Become the stuff of legend, or die trying.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
